[package]
name = "pngme"
version = "0.1.0"
authors = ["Tirth Jain <jaintirth24@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
byteorder = "1"
crc = "1.8.1"
structopt = "0.3.15"

